{%set name = "sklearn-contrib-lightning" %}
{%set version = "0.5.0" %}
{%set hash_type = "md5" %}
{%set hash_val = "b1a3074f25fe5b0c4aa6b71e410d21a5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy 1.11.*
    - cython
    - scikit-learn
  run:
    - python
    - numpy >=1.11
    - scikit-learn

test:
  requires:
    - numpy
    - scikit-learn
    - nose
  imports:
    - lightning

about:
  home: http://contrib.scikit-learn.org/lightning/
  license: BSD 3-Clause
  summary: lightning is a library for large-scale linear classification, regression and ranking in Python.

extra:
  recipe-maintainers:
    - fabianp
    - mblondel
