{% set name = "sklearn-contrib-lightning" %}
{% set version = "0.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {fc27cd40bb81faf4cc1fe91d983c87097dd323afbf0935b51beaa3fe1835c09d

build:
  number: 1001
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
    - scikit-learn
  run:
    - python
    - numpy
    - scikit-learn

test:
  requires:
    - numpy
    - scikit-learn
    - nose
  imports:
    - lightning

about:
  home: http://contrib.scikit-learn.org/lightning/
  license: BSD 3-Clause
  summary: lightning is a library for large-scale linear classification, regression and ranking in Python.

extra:
  recipe-maintainers:
    - fabianp
    - mblondel
