{% set version = "0.6.0" %}

package:
  name: sklearn-contrib-lightning
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sklearn-contrib-lightning/sklearn-contrib-lightning-{{ version }}.tar.gz
  sha256: ec21510ebc4f472a757b441eccb796398b193966c431b8178a1d52509d73a76e
  patches:
    - fix_tests.patch 

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - numpy 
    - cython
    - scikit-learn
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scikit-learn

test:
  requires:
    - numpy
    - scikit-learn
    - nose
  imports:
    - lightning

about:
  home: https://contrib.scikit-learn.org/lightning/
  doc_url: https://contrib.scikit-learn.org/lightning/
  dev_url: https://github.com/scikit-learn-contrib/lightning
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: lightning is a library for large-scale linear classification, regression and ranking in Python.

extra:
  recipe-maintainers:
    - fabianp
    - mblondel
