travis:
  secure:
    BINSTAR_TOKEN: UJ9XpMFGpIlQVoIPkCPmBVaUb9jEtPCu+NMYOSQ/z+hanpWGJkfxIOw34KQ7eiYXx1Slmko+LWtRRgvEYpe3PTd9ZqvLdLnMaCgHg1T6rKuGqA/diAfxUTGWUHzHNSr8/7ZPibVq2JE1tbsqQLFvViKTcRn3ZS1AOzGtGq9HteJHTvynKDU2qjCTZZs+Fujpp4mJtLvdg8dk7SwlUD+3MUc6RRX90UzKVlnEmDfV6KIQT2JZFnIXRxXqKiarVHVh6cp61WIu1pzRbt3+GLA37CfntikAGFsQ0i+DRAIgUFuUUxjuWsBONXMxHNeBZfXkVHbVRwJrxq/CSpwSvXmFAKIRqeeA6i+vYztM5WTb0z1RJc6LdlRFSdXyL+58C5rOzi6fxCYZlUm/IfGLel0k7JeMUBbmWeCZajDpkezYNrVUN8/UmE48rI0uEC8X/X2zneSdM2pFmM0lAAx+Z9nJk2vKWKKEuW7mqlnor9uJuEBlz5eANO+muti1n8B/RFqRy3EQKhuyzG1ffhH+JyGPPy2AQ7gobMpPCwxfbw8HQqBZy9r+aS0KvMKInxTL0l6U8R0OXuJIKjQNIwDzwnNapU0A/m39Rx32s4YR0I6FPsRjCDSX0qJBpdxf5PRAWoGRaGHKnjKYEFMhcFf50MKz3+d+cT2Rmgq4jRgHS9v+OEw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
